trigger:
  - develop
  - master

pr: none

pool:
  vmImage: windows-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildManifest
        displayName: Build Manifest
        variables:
          solutionDir: manifest
        steps:
          - task: ReplaceTokens@3
            displayName: Replace tokens
            inputs:
              rootDirectory: $(solutionDir)
              targetFiles: manifest.json
              encoding: utf-8
              writeBOM: false
              actionOnMissing: fail
              keepToken: false
              tokenPrefix: "{{"
              tokenSuffix: "}}"
          - task: ArchiveFiles@2
            displayName: Archive build files
            inputs:
              rootFolderOrFile: $(solutionDir)
              archiveFile: $(Build.ArtifactStagingDirectory)/manifest.zip
              includeRootFolder: false
          - task: PublishPipelineArtifact@1
            displayName: Publish artifacts
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: manifest
              publishLocation: pipeline
      - job: BuildServer
        displayName: Build Server
        variables:
          buildConfiguration: Release
          solutionDir: source/server
          solutionFile: Karamem0.Teamtile.csproj
        steps:
          - task: DotNetCoreCLI@2
            displayName: Run dotnet restore
            inputs:
              command: restore
              projects: $(solutionDir)/$(solutionFile)
          - task: DotNetCoreCLI@2
            displayName: Run dotnet publish
            inputs:
              command: publish
              projects: $(solutionDir)/$(solutionFile)
              arguments: --configuration $(buildConfiguration) --output $(solutionDir)/publish
              publishWebProjects: true
              zipAfterPublish: false
          - task: ArchiveFiles@2
            displayName: Archive build files
            inputs:
              rootFolderOrFile: $(solutionDir)/publish/server
              archiveFile: $(Build.ArtifactStagingDirectory)/server.zip
              includeRootFolder: false
          - task: PublishPipelineArtifact@1
            displayName: Publish artifacts
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: server
              publishLocation: pipeline
      - job: BuildClient
        displayName: Build Client
        variables:
          solutionDir: source/client
        steps:
          - task: ReplaceTokens@3
            displayName: Replace tokens
            inputs:
              rootDirectory: $(solutionDir)
              targetFiles: .env
              encoding: utf-8
              writeBOM: false
              actionOnMissing: fail
              keepToken: false
              tokenPrefix: "{{"
              tokenSuffix: "}}"
          - task: NodeTool@0
            displayName: Install Node.js
            inputs:
              versionSpec: 14.x
          - task: Npm@1
            displayName: Run npm install
            inputs:
              command: install
              workingDir: $(solutionDir)
          - task: Npm@1
            displayName: Run npm run test
            inputs:
              command: custom
              customCommand: run test-ci
              workingDir: $(solutionDir)
          - task: Npm@1
            displayName: Run npm run build
            inputs:
              command: custom
              customCommand: run build
              workingDir: $(solutionDir)
          - task: CopyFiles@2
            displayName: Copy web.config
            inputs:
              sourceFolder: $(solutionDir)
              contents: web.config
              targetFolder: $(solutionDir)/build
          - task: ArchiveFiles@2
            displayName: Archive build files
            inputs:
              rootFolderOrFile: $(solutionDir)/build
              archiveFile: $(Build.ArtifactStagingDirectory)/client.zip
              includeRootFolder: false
          - task: PublishTestResults@2
            displayName: Publish test results
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: $(solutionDir)/junit.xml
          - task: PublishPipelineArtifact@1
            displayName: Publish artifacts
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifact: client
              publishLocation: pipeline
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            displayName: Download build artifacts
            inputs:
              buildType: current
              targetPath: $(Build.ArtifactStagingDirectory)
          - task: ExtractFiles@1
            displayName: Extract server files
            inputs:
              archiveFilePatterns: $(Build.ArtifactStagingDirectory)/**/server.zip
              destinationFolder: $(System.ArtifactsDirectory)/deploy/api
              cleanDestinationFolder: false
              overwriteExistingFiles: false
          - task: ExtractFiles@1
            displayName: Extract client files
            inputs:
              archiveFilePatterns: $(Build.ArtifactStagingDirectory)/**/client.zip
              destinationFolder: $(System.ArtifactsDirectory)/deploy
              cleanDestinationFolder: false
              overwriteExistingFiles: false
          - task: ArchiveFiles@2
            displayName: Archive files
            inputs:
              rootFolderOrFile: $(System.ArtifactsDirectory)/deploy
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(System.ArtifactsDirectory)/deploy.zip
              replaceExistingArchive: true
          - task: AzureWebApp@1
            displayName: Deploy files
            inputs:
              azureSubscription: Azure Resource Manager
              appType: webApp
              appName: teamtile
              package: $(System.ArtifactsDirectory)/deploy.zip
