name: Deploy to GitHub Release

description: This GitHub Action deploys built artifacts to GitHub Release.

runs:
  using: composite
  steps:
    - name: Create release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
