name: Build source

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions: {}

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Update microsoft-identity-association.json
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{MSAL_APP_ID}}", "${{vars.MSAL_APP_ID}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: source/client/public/.well-known/microsoft-identity-association.json
      - name: Update .env
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{MSAL_APP_ID}}", "${{vars.MSAL_APP_ID}}"
          $content = $content -Replace "{{MSAL_TENANT_ID}}", "${{vars.MSAL_TENANT_ID}}"
          $content = $content -Replace "{{HOST_NAME}}", "${{vars.HOST_NAME}}"
          $content = $content -Replace "{{TELEMETRY_CONNECTION_STRING}}", "${{vars.TELEMETRY_CONNECTION_STRING}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: source/client/.env
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}} --no-git-tag-version
        working-directory: source/client
      - name: Restore client
        run: npm ci
        working-directory: source/client
      - name: Build client
        run: npm run build
        working-directory: source/client
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore server
        run: dotnet restore
        working-directory: source/server
      - name: Build server
        shell: pwsh
        run: |
          dotnet publish `
            Karamem0.Teamtile/Karamem0.Teamtile.csproj `
            -c Release `
            -p:PublishDir=${{github.workspace}}/source/server/build `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
        working-directory: source/server
      - name: Upload artifatcs
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: source/server/build
          include-hidden-files: true
