name: Build manifest

on:
  workflow_call: {}

permissions: {}

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Update manifest.json
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{MICROSOFT_APP_ID}}", "${{vars.MICROSOFT_APP_ID}}"
          $content = $content -Replace "{{AZURE_WEB_APP_DOMAIN_NAME}}", "${{vars.AZURE_WEB_APP_DOMAIN_NAME}}"
          $content = $content -Replace "{{APP_VERSION}}", "${{vars.BUILD_VERSION}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: manifest/manifest.json
      - name: Upload artifatcs
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest
