name: Deploy to GitHub Release

on:
  workflow_call: {}

permissions:
  contents: write

env:
  RELEASE_FILE_NAME: Teamtile_${{vars.BUILD_VERSION}}.zip

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Download artifatcs
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: manifest
      - name: Archive artifatcs
        shell: pwsh
        run: Compress-Archive -Path manifest/* -DestinationPath ${{env.RELEASE_FILE_NAME}}
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.RELEASE_FILE_NAME}}
