on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    environment:
      name: development
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Rewrite .env
        run: |
          $content = Get-Content -Path source/client/.env
          $content = $content -replace "{{AppId}}", "${{secrets.APP_CLIENT_ID}}"
          $content = $content -replace "{{TenantId}}", "${{secrets.APP_TENANT_ID}}"
          $content = $content -replace "{{ConnectionString}}", "${{secrets.APPLICATIONINSIGHTS_CONNECTION_STRING}}"
          Out-File -FilePath source/client/.env -InputObject $content -Encoding UTF8
      - name: Restore client
        run: npm ci
        working-directory: source/client
      - name: Audit client
        run: npm audit
        working-directory: source/client
      - name: Build client
        run: npm run build
        working-directory: source/client
      - name: Test client
        run: npm run test:ci
        working-directory: source/client
      - name: Publish test results
        uses: enricomi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: source/client/coverage/junit.xml
          check_name: test results
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Restore server
        run: dotnet restore source/server
      - name: Build server
        run: dotnet publish source/server -c Release -p:PublishDir=build
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: teamtile-build
          path: source/server/build
      - name: Rewrite manifest.json
        run: |
          $content = Get-Content -Path manifest/manifest.json
          $content = $content -replace "{{AppId}}", "${{secrets.APP_CLIENT_ID}}"
          $content = $content -replace "{{AppDomain}}", "${{secrets.APP_DOMAIN}}"
          Out-File -FilePath manifest/manifest.json -InputObject $content -Encoding UTF8
      - name: Upload manifest files
        uses: actions/upload-artifact@v3
        with:
          name: teamtile-manifest
          path: manifest
  deploy:
    needs: build
    runs-on: windows-latest
    environment:
      name: development
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: teamtile-build
          path: build
      - name: Connect to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.APP_NAME}}
          package: build
