name: Trigger on tags

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  deploy-to-github-release:
    name: Deploy to GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Deploy to GitHub Release
        uses: ./.github/actions/deploy-to-github-release
