name: Trigger on develop

on:
  push:
    branches:
      - develop

permissions:
  checks: write

jobs:
  test:
    name: Test source
    uses: ./.github/workflows/test-source.yml
    secrets: inherit
    with:
      environment: dev
  build-source:
    name: Build source
    needs: test
    uses: ./.github/workflows/build-source.yml
    secrets: inherit
    with:
      environment: dev
  build-manifest:
    name: Build manifest
    uses: ./.github/workflows/build-manifest.yml
    secrets: inherit
    with:
      environment: dev
  deploy:
    name: Deploy to Azure
    needs: build-source
    uses: ./.github/workflows/deploy-to-azure.yml
    secrets: inherit
    with:
      environment: dev
