name: Trigger on main

on:
  push:
    branches:
      - main

permissions:
  checks: write

jobs:
  build-source:
    name: Build source
    uses: ./.github/workflows/build-source.yml
    secrets: inherit
    with:
      environment: prd
  build-manifest:
    name: Build manifest
    uses: ./.github/workflows/build-manifest.yml
    secrets: inherit
    with:
      environment: prd
  deploy:
    name: Deploy to Azure
    needs: build-source
    uses: ./.github/workflows/deploy-to-azure.yml
    secrets: inherit
    with:
      environment: prd
