name: Trigger on tags

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build-manifest:
    name: Build manifest
    uses: ./.github/workflows/build-manifest.yml
    secrets: inherit
    with:
      environment: prd
  release:
    name: Deploy to GitHub Release
    needs: build-manifest
    uses: ./.github/workflows/deploy-to-github-release.yml
    secrets: inherit
